// biome-ignore-all lint/performance/noBarrelFile: the studio's single seam for the three workspace packages
/* The studio's view of @bleepkit/core, @bleepkit/core/tools and @bleepkit/sfx. Every view imports from here, so a
   rename in a package is fixed in one place. */
export {
  chipChannels,
  chipProfile,
  defaultInstrument,
  defaultProject,
  defaultSfx,
  defaultSong,
  deriveSeed,
  formatEffect,
  generateSample,
  hashString,
  hzToNote,
  issuesToText,
  mmlToTrack,
  mulberry32,
  normalizeInstrument,
  normalizeProject,
  normalizeSfx,
  normalizeSong,
  noteName,
  noteToHz,
  parseEffect,
  parseMml,
  parseNoteName,
  patternToMml,
  renderInstrumentNote,
  renderSfx,
  renderSong,
  SAMPLE_GENERATORS,
} from "@bleepkit/core";
export {
  type Analysis,
  analyze,
  encodeMp3,
  encodeOgg,
  encodeWav,
  fft as realFft,
  MP3_ENCODER_DELAY,
  type PngImage as PixelImage,
  scopesImage,
  spectrogramImage,
  waveformImage,
} from "@bleepkit/core/tools";
export {
  describeSfx,
  generateSfx,
  mutateMany,
  mutateSfx,
  randomizeSfx,
} from "@bleepkit/sfx";
