// The generated audio.ts / manifest.json (architecture.md section 7). The strongest checks run the generated module
// and compare what it exports with the manifest it was made from; audio-ts.test.ts type-checks the real `export`
// output against @bleepkit/player.

import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import vm from "node:vm";
import type { AudioManifest, ManifestSfx } from "@bleepkit/core";
import { describe, expect, it } from "vitest";
import {
  manifestJson,
  manifestTs,
  mp3Shift,
  seconds,
  tsLiteral,
} from "../src/manifest.ts";
import { MP3_ENCODER_DELAY_FRAMES } from "../src/render.ts";
import { tempDir } from "./helpers.ts";

/** The character the house rules forbid in generated text, written as a code so this file has none. */
const EM_DASH = String.fromCharCode(0x20_14);

const manifest: AudioManifest = {
  base: "/audio/",
  sampleRate: 48_000,
  sfx: {
    coin: { duration: 0.31, file: "coin.ogg" },
    "coin-2": { duration: 0.4, file: "coin-2.ogg" },
  },
  songs: {
    "boss-2": {
      duration: 10,
      file: "boss-2.ogg",
      loopEnd: null,
      loopStart: null,
    },
    title: {
      duration: 25,
      events: "title.events.json",
      file: "title.ogg",
      loopEnd: 24,
      loopStart: 4.8,
    },
  },
};

let counter = 0;

/** Writes `audio.ts` text to a temp file and imports it: Node strips the type syntax, so the values are what a game gets. */
async function evaluate(source: string): Promise<{
  manifest: unknown;
  sfx: unknown;
  songs: unknown;
}> {
  counter += 1;
  const file = path.join(tempDir("bleepkit-manifest-"), `audio-${counter}.ts`);
  fs.writeFileSync(file, source);
  return await import(/* @vite-ignore */ pathToFileURL(file).href);
}

describe("manifestTs", () => {
  it("exports sfx, songs and manifest values equal to the manifest it was made from", async () => {
    const mod = await evaluate(manifestTs(manifest));
    expect(mod.manifest).toEqual(manifest);
    expect(mod.sfx).toEqual({ coin: "coin.ogg", "coin-2": "coin-2.ogg" });
    expect(mod.songs).toEqual({
      "boss-2": {
        duration: 10,
        file: "boss-2.ogg",
        loopEnd: null,
        loopStart: null,
      },
      title: { duration: 25, file: "title.ogg", loopEnd: 24, loopStart: 4.8 },
    });
  });

  it("carries embedded documents through unchanged, nested arrays included", async () => {
    const data = {
      arpeggio: { rate: 8, steps: [3, 7, 12] },
      category: "coin",
      layers: [
        { name: "a", values: [0.5, -1] },
        { name: "b-c", values: [] },
      ],
      note: 'say "hi"\nnext',
    } as unknown as NonNullable<ManifestSfx["data"]>;
    const embedded: AudioManifest = {
      ...manifest,
      sfx: { coin: { data, duration: 0.31, file: "coin.ogg" } },
    };
    const mod = await evaluate(manifestTs(embedded));
    expect(mod.manifest).toEqual(embedded);
    // the sfx and songs summaries stay the plain file maps
    expect(mod.sfx).toEqual({ coin: "coin.ogg" });
  });

  it("is valid for an empty manifest", async () => {
    const empty: AudioManifest = {
      base: "/",
      sampleRate: 44_100,
      sfx: {},
      songs: {},
    };
    const mod = await evaluate(manifestTs(empty));
    expect(mod.manifest).toEqual(empty);
    expect(mod.sfx).toEqual({});
    expect(mod.songs).toEqual({});
  });

  it("has the shape section 7 prescribes: type-only import, id types, `as const satisfies`", () => {
    const ts = manifestTs(manifest);
    expect(
      ts.startsWith("/* Generated by bleepkit export. Do not edit. */\n")
    ).toBe(true);
    expect(ts).toContain(
      'import type { AudioManifest } from "@bleepkit/player";'
    );
    expect(ts).toContain("export type SfxId = keyof typeof sfx;");
    expect(ts).toContain("export type SongId = keyof typeof songs;");
    // an `: AudioManifest` annotation would widen the ids to string (see section 7)
    expect(ts).toContain("} as const satisfies AudioManifest;");
    expect(ts).not.toContain("manifest: AudioManifest");
    // a dashed id is quoted as a key, a plain one is not
    expect(ts).toContain('  "coin-2": "coin-2.ogg",');
    expect(ts).toContain('  coin: "coin.ogg",');
    expect(ts).not.toContain(EM_DASH);
  });

  it("imports ManifestSfx and ManifestSong only when documents are embedded", () => {
    const withData = {
      ...manifest,
      sfx: {
        coin: {
          data: {} as NonNullable<ManifestSfx["data"]>,
          duration: 1,
          file: "c.ogg",
        },
      },
    };
    expect(manifestTs(withData)).toContain(
      'import type { AudioManifest, ManifestSfx, ManifestSong } from "@bleepkit/player";'
    );
    expect(manifestTs(manifest)).not.toContain("ManifestSfx");
  });
});

describe("tsLiteral", () => {
  it("prints a value that evaluates back to the same value", () => {
    const value = {
      "9lives": [1.5, -2, 0, 1e-7],
      "b-c": null,
      empty: { list: [], obj: {} },
      flag: false,
      nested: [{ x: 1 }, { y: [{ z: "deep" }] }],
      text: 'quote " backslash \\ newline \n tab \t unicode é line sep  ',
    };
    const evaluated = vm.runInNewContext(`(${tsLiteral(value)})`) as unknown;
    expect(JSON.parse(JSON.stringify(evaluated))).toEqual(value);
  });

  it("leaves out properties whose value is undefined", () => {
    const evaluated = vm.runInNewContext(
      `(${tsLiteral({ drop: undefined, keep: 1 })})`
    ) as Record<string, unknown>;
    expect(Object.keys(evaluated)).toEqual(["keep"]);
  });
});

describe("manifest.json and timing helpers", () => {
  it("manifestJson is the manifest as JSON with a final newline", () => {
    const text = manifestJson(manifest);
    expect(JSON.parse(text)).toEqual(manifest);
    expect(text.endsWith("}\n")).toBe(true);
  });

  it("shifts mp3 loop points by 1105 frames of encoder delay (section 8)", () => {
    expect(MP3_ENCODER_DELAY_FRAMES).toBe(1105);
    expect(mp3Shift(48_000)).toBeCloseTo(0.023_020_833, 8);
    expect(mp3Shift(44_100)).toBeCloseTo(0.025_056_689, 8);
  });

  it("seconds keeps microsecond precision and drops float noise", () => {
    expect(seconds(1.234_567_89)).toBe(1.234_568);
    expect(seconds(0.1 + 0.2)).toBe(0.3);
    expect(seconds(24)).toBe(24);
  });
});
