import type { AudioManifest } from "@bleepkit/core";
import { describe, expect, it } from "vitest";
import {
  MP3_LOOP_WARNING,
  manifestJson,
  manifestTs,
  mp3Shift,
  seconds,
  tsLiteral,
} from "../src/manifest.ts";
import { MP3_ENCODER_DELAY_FRAMES } from "../src/render.ts";

const manifest: AudioManifest = {
  base: "/audio/",
  sampleRate: 48_000,
  sfx: {
    coin: { duration: 0.31, file: "coin.ogg" },
    "coin-2": { duration: 0.4, file: "coin-2.ogg" },
  },
  songs: {
    title: {
      duration: 25,
      events: "title.events.json",
      file: "title.ogg",
      loopEnd: 24,
      loopStart: 4.8,
    },
  },
};

describe("manifest", () => {
  it("writes the typed audio.ts of section 7", () => {
    const ts = manifestTs(manifest);
    expect(ts).toContain("/* Generated by bleepkit export. Do not edit. */");
    expect(ts).toContain(
      'import type { AudioManifest } from "@bleepkit/player";'
    );
    expect(ts).toContain(
      'export const sfx = {\n  coin: "coin.ogg",\n  "coin-2": "coin-2.ogg",\n} as const;'
    );
    expect(ts).toContain(
      'title: { duration: 25, file: "title.ogg", loopEnd: 24, loopStart: 4.8 }'
    );
    expect(ts).toContain("export type SfxId = keyof typeof sfx;");
    expect(ts).toContain("export type SongId = keyof typeof songs;");
    expect(ts).toContain("export const manifest = {");
    expect(ts).toContain("} as const satisfies AudioManifest;");
    expect(ts).not.toContain("manifest: AudioManifest");
    expect(ts).toContain('base: "/audio/"');
    expect(ts).toContain('"coin-2": {');
    expect(ts.includes("\u2014")).toBe(false);
  });

  it("writes an empty manifest as valid TypeScript", () => {
    const ts = manifestTs({
      base: "/",
      sampleRate: 48_000,
      sfx: {},
      songs: {},
    });
    expect(ts).toContain("export const sfx = {} as const;");
    expect(ts).toContain("export const songs = {} as const;");
  });

  it("is deterministic and keeps manifest.json equal to the object", () => {
    expect(manifestTs(manifest)).toBe(manifestTs(structuredClone(manifest)));
    expect(JSON.parse(manifestJson(manifest))).toEqual(manifest);
  });

  it("prints nested arrays and strings as TypeScript literals", () => {
    expect(tsLiteral({ a: [1, 2], "b-c": null, d: [{ x: 1 }] })).toBe(
      '{\n  a: [1, 2],\n  "b-c": null,\n  d: [\n    {\n      x: 1,\n    },\n  ],\n}'
    );
  });

  it("shifts mp3 loop points by the encoder delay and keeps microsecond precision", () => {
    expect(MP3_ENCODER_DELAY_FRAMES).toBe(1105);
    expect(mp3Shift(48_000)).toBeCloseTo(1105 / 48_000, 9);
    expect(seconds(1.234_567_89)).toBe(1.234_568);
    expect(MP3_LOOP_WARNING).toBe(
      "MP3 loop points are approximate; use OGG for seamless loops"
    );
  });
});
