// The typed audio manifest (architecture.md section 7): audio.ts for games, manifest.json for loadManifest.
// Pure functions, no file system, so the output is easy to test.
import { MP3_ENCODER_DELAY_FRAMES } from "./render.ts";
import type { AudioManifest } from "./stubs.ts";

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export const MP3_LOOP_WARNING =
  "MP3 loop points are approximate; use OGG for seamless loops";

function key(k: string): string {
  return IDENT.test(k) ? k : JSON.stringify(k);
}

/** A TypeScript object literal: unquoted identifier keys, two space indent, JSON values. */
export function tsLiteral(value: unknown, depth = 0): string {
  const pad = "  ".repeat(depth);
  const inner = "  ".repeat(depth + 1);
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]";
    }
    if (value.every((v) => v === null || typeof v !== "object")) {
      return `[${value.map((v) => JSON.stringify(v)).join(", ")}]`;
    }
    return `[\n${value.map((v) => inner + tsLiteral(v, depth + 1)).join(",\n")},\n${pad}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined
    );
    if (entries.length === 0) {
      return "{}";
    }
    return `{\n${entries.map(([k, v]) => `${inner}${key(k)}: ${tsLiteral(v, depth + 1)}`).join(",\n")},\n${pad}}`;
  }
  // JSON.stringify returns undefined for undefined, functions and symbols
  // biome-ignore lint/suspicious/noUnnecessaryConditions: the type lies
  return JSON.stringify(value) ?? "null";
}

/** Seconds, enough digits that a loop point lands on the same sample after decoding (1 microsecond). */
export function seconds(value: number): number {
  return Number(value.toFixed(6));
}

/** MP3 decoders add encoder delay at the start, so loop points shift by it (the manifest compensates). */
export function mp3Shift(sampleRate: number): number {
  return MP3_ENCODER_DELAY_FRAMES / sampleRate;
}

function sorted<T>(obj: Record<string, T>): Record<string, T> {
  return Object.fromEntries(
    Object.entries(obj).sort(([a], [b]) => (a < b ? -1 : 1))
  );
}

export function manifestTs(manifest: AudioManifest): string {
  const sfxFiles = Object.fromEntries(
    Object.entries(manifest.sfx).map(([id, s]) => [id, s.file])
  );
  const songSummary = Object.fromEntries(
    Object.entries(manifest.songs).map(([id, s]) => [
      id,
      {
        duration: s.duration,
        file: s.file,
        loopEnd: s.loopEnd,
        loopStart: s.loopStart,
      },
    ])
  );
  const oneLine = (o: Record<string, unknown>): string => {
    const entries = Object.entries(o);
    if (entries.length === 0) {
      return "{}";
    }
    return `{\n${entries
      .map(([id, v]) => {
        const text =
          typeof v === "string"
            ? JSON.stringify(v)
            : `{ ${Object.entries(v as Record<string, unknown>)
                .map(([k, x]) => `${key(k)}: ${JSON.stringify(x)}`)
                .join(", ")} }`;
        return `  ${key(id)}: ${text},`;
      })
      .join("\n")}\n}`;
  };
  return [
    "/* Generated by bleepkit export. Do not edit. */",
    'import type { AudioManifest } from "@bleepkit/player";',
    "",
    `export const sfx = ${oneLine(sfxFiles)} as const;`,
    "",
    `export const songs = ${oneLine(songSummary)} as const;`,
    "",
    "export type SfxId = keyof typeof sfx;",
    "export type SongId = keyof typeof songs;",
    "",
    `export const manifest: AudioManifest = ${tsLiteral(manifest)};`,
    "",
  ].join("\n");
}

export function manifestJson(manifest: AudioManifest): string {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export { sorted as sortedRecord };
