/* The typed manifest (architecture section 7): the studio builds the same text the CLI writes to audio.ts, for the live
   preview on the project page and for exporting from the browser. */
import type { Instrument, Project, Sfx, Song } from "./lib/contract.ts";

export interface SfxEntry {
  data?: Sfx;
  duration: number;
  file: string;
}
export interface SongEntry {
  data?: { song: Song; instruments: Record<string, Instrument> };
  duration: number;
  events?: string;
  file: string;
  loopEnd: number | null;
  loopStart: number | null;
}
export interface Manifest {
  base: string;
  sampleRate: number;
  sfx: Record<string, SfxEntry>;
  songs: Record<string, SongEntry>;
}

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const q = (k: string) => (IDENT.test(k) ? k : JSON.stringify(k));
const round = (n: number) => Math.round(n * 1000) / 1000;

/** A TypeScript literal for plain data: unquoted identifier keys, double quoted strings, two space indent. */
export function tsLiteral(value: unknown, depth = 0): string {
  const pad = "  ".repeat(depth + 1);
  const end = "  ".repeat(depth);
  if (Array.isArray(value)) {
    if (value.every((v) => typeof v !== "object" || v === null)) {
      return `[${value.map((v) => tsLiteral(v)).join(", ")}]`;
    }
    return `[\n${value.map((v) => `${pad}${tsLiteral(v, depth + 1)}`).join(",\n")},\n${end}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined
    );
    if (entries.length === 0) {
      return "{}";
    }
    return `{\n${entries.map(([k, v]) => `${pad}${q(k)}: ${tsLiteral(v, depth + 1)}`).join(",\n")},\n${end}}`;
  }
  return JSON.stringify(value);
}

const oneLine = (o: Record<string, unknown>) =>
  `{ ${Object.entries(o)
    .map(([k, v]) => `${q(k)}: ${JSON.stringify(v)}`)
    .join(", ")} }`;

export function manifestTs(m: Manifest): string {
  const sfxFiles = Object.fromEntries(
    Object.entries(m.sfx).map(([id, e]) => [id, e.file])
  );
  const songSummary = Object.fromEntries(
    Object.entries(m.songs).map(([id, e]) => [
      id,
      {
        file: e.file,
        ...(e.loopStart === null ? {} : { loopStart: e.loopStart }),
        ...(e.loopEnd === null ? {} : { loopEnd: e.loopEnd }),
        duration: e.duration,
      },
    ])
  );
  const songLine = (o: Record<string, unknown>) =>
    `{\n${Object.entries(o)
      .map(([k, v]) => `  ${q(k)}: ${oneLine(v as Record<string, unknown>)}`)
      .join(",\n")},\n}`;
  return [
    "/* Generated by bleepkit export. Do not edit. */",
    'import type { AudioManifest } from "@bleepkit/player";',
    "",
    `export const sfx = ${
      Object.keys(sfxFiles).length
        ? `{\n${Object.entries(sfxFiles)
            .map(([k, v]) => `  ${q(k)}: ${JSON.stringify(v)}`)
            .join(",\n")},\n}`
        : "{}"
    } as const;`,
    "",
    `export const songs = ${Object.keys(songSummary).length ? songLine(songSummary) : "{}"} as const;`,
    "",
    "export type SfxId = keyof typeof sfx;",
    "export type SongId = keyof typeof songs;",
    "",
    `export const manifest: AudioManifest = ${tsLiteral(m)};`,
    "",
  ].join("\n");
}

export const manifestJson = (m: Manifest): string =>
  `${JSON.stringify(m, null, 2)}\n`;

const EXT = (f: string) => f;

/** What the manifest will probably say, from the documents alone (real durations come from rendering). */
export function previewManifest(
  p: Project,
  sfx: readonly { id: string; value: Sfx }[],
  songs: readonly { id: string; value: Song }[],
  instruments: Record<string, Instrument>
): Manifest {
  const m: Manifest = {
    base: p.export.baseUrl,
    sampleRate: p.sampleRate,
    sfx: {},
    songs: {},
  };
  for (const s of sfx) {
    const dur =
      s.value.envelope.attack +
      s.value.envelope.sustain +
      s.value.envelope.decay +
      0.25;
    const e: SfxEntry = {
      duration: round(dur),
      file: EXT(`${s.id}.${p.export.sfxFormat}`),
    };
    if (p.export.embed) {
      e.data = s.value;
    }
    m.sfx[s.id] = e;
  }
  for (const s of songs) {
    const song = s.value;
    const secPerRow = 60 / (song.tempo * song.rowsPerBeat);
    let rows = 0;
    let loopRows = 0;
    song.order.forEach((pid, i) => {
      const len = song.patterns[pid]?.length ?? 0;
      if (song.loop !== null && i === song.loop) {
        loopRows = rows;
      }
      rows += len;
    });
    const duration = round(rows * secPerRow + 1);
    const e: SongEntry = {
      duration,
      file: EXT(`${s.id}.${p.export.musicFormat}`),
      loopEnd: song.loop === null ? null : round(rows * secPerRow),
      loopStart: song.loop === null ? null : round(loopRows * secPerRow),
      ...(p.export.events ? { events: `${s.id}.events.json` } : {}),
    };
    if (p.export.embed) {
      e.data = { instruments, song };
    }
    m.songs[s.id] = e;
  }
  return m;
}

/** "../public/audio" becomes "public/audio": where a zip of the game project keeps the file. */
export function cleanPath(p: string): string {
  const parts: string[] = [];
  for (const seg of p.split("/")) {
    if (seg === "" || seg === ".") {
      continue;
    }
    if (seg === "..") {
      continue;
    }
    parts.push(seg);
  }
  return parts.join("/");
}
