/* What the studio shows and writes as the manifest when there is no CLI around: the preview on the project page and
   the audio.ts in the zip that "Export in this browser" downloads. It is deliberately plain: the data as JSON, with the
   same exports as the real file (`sfx`, `songs`, `manifest` and the id types). The typed, tidily formatted audio.ts is
   written by `bleepkit export` (packages/cli/src/manifest.ts), and the studio does not reimplement that writer. */
import type { Instrument, Project, Sfx, Song } from "./lib/contract.ts";

export interface SfxEntry {
  data?: Sfx;
  duration: number;
  file: string;
}
export interface SongEntry {
  data?: { song: Song; instruments: Record<string, Instrument> };
  duration: number;
  events?: string;
  file: string;
  loopEnd: number | null;
  loopStart: number | null;
}
export interface Manifest {
  base: string;
  sampleRate: number;
  sfx: Record<string, SfxEntry>;
  songs: Record<string, SongEntry>;
}

const round = (n: number) => Math.round(n * 1000) / 1000;
const json = (value: unknown) => JSON.stringify(value, null, 2);

/** The manifest as a TypeScript module. JSON is a valid TypeScript expression, so there is no literal writer here. */
export function manifestTs(m: Manifest): string {
  const files = Object.fromEntries(
    Object.entries(m.sfx).map(([id, e]) => [id, e.file])
  );
  const songs = Object.fromEntries(
    Object.entries(m.songs).map(([id, e]) => [
      id,
      {
        duration: e.duration,
        file: e.file,
        ...(e.loopStart === null ? {} : { loopStart: e.loopStart }),
        ...(e.loopEnd === null ? {} : { loopEnd: e.loopEnd }),
      },
    ])
  );
  return [
    "/* Generated by the Bleepkit studio in the browser. Do not edit. */",
    'import type { AudioManifest } from "@bleepkit/player";',
    "",
    `export const sfx = ${json(files)} as const;`,
    "",
    `export const songs = ${json(songs)} as const;`,
    "",
    "export type SfxId = keyof typeof sfx;",
    "export type SongId = keyof typeof songs;",
    "",
    `export const manifest: AudioManifest = ${json(m)};`,
    "",
  ].join("\n");
}

export const manifestJson = (m: Manifest): string => `${json(m)}\n`;

function previewSfx(p: Project, id: string, sfx: Sfx): SfxEntry {
  const { attack, sustain, decay } = sfx.envelope;
  const e: SfxEntry = {
    duration: round(attack + sustain + decay + 0.25),
    file: `${id}.${p.export.sfxFormat}`,
  };
  if (p.export.embed) {
    e.data = sfx;
  }
  return e;
}

/** The song's length in rows and the row its loop starts on, from the order list. */
function songRows(song: Song): { loopRows: number; rows: number } {
  let rows = 0;
  let loopRows = 0;
  song.order.forEach((pid, i) => {
    if (i === song.loop) {
      loopRows = rows;
    }
    rows += song.patterns[pid]?.length ?? 0;
  });
  return { loopRows, rows };
}

function previewSong(
  p: Project,
  id: string,
  song: Song,
  instruments: Record<string, Instrument>
): SongEntry {
  const secPerRow = 60 / (song.tempo * song.rowsPerBeat);
  const { loopRows, rows } = songRows(song);
  const looped = song.loop !== null;
  const e: SongEntry = {
    duration: round(rows * secPerRow + 1),
    file: `${id}.${p.export.musicFormat}`,
    loopEnd: looped ? round(rows * secPerRow) : null,
    loopStart: looped ? round(loopRows * secPerRow) : null,
    ...(p.export.events ? { events: `${id}.events.json` } : {}),
  };
  if (p.export.embed) {
    e.data = { instruments, song };
  }
  return e;
}

/** What the manifest will probably say, from the documents alone (real durations come from rendering). */
export function previewManifest(
  p: Project,
  sfx: readonly { id: string; value: Sfx }[],
  songs: readonly { id: string; value: Song }[],
  instruments: Record<string, Instrument>
): Manifest {
  return {
    base: p.export.baseUrl,
    sampleRate: p.sampleRate,
    sfx: Object.fromEntries(
      sfx.map((s) => [s.id, previewSfx(p, s.id, s.value)])
    ),
    songs: Object.fromEntries(
      songs.map((s) => [s.id, previewSong(p, s.id, s.value, instruments)])
    ),
  };
}

/** "../public/audio" becomes "public/audio": where a zip of the game project keeps the file. */
export const cleanPath = (p: string): string =>
  p
    .split("/")
    .filter((seg) => seg !== "" && seg !== "." && seg !== "..")
    .join("/");
